stages:
  - check
  - test
  - build-debug
  - build-release

default:
  image: rust:latest
  before_script:
    - rustup component add rustfmt
    - rustup component add clippy

format:
  stage: check
  script:
    - cargo fmt --verbose -- --check --verbose
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
      allow_failure: false
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      allow_failure: false
    - if: $CI_COMMIT_BRANCH == "master"
      allow_failure: false
    - when: always

clippy:
  stage: check
  script:
    - cargo clippy --verbose --all-targets --all-features -- -D warnings --verbose
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
      allow_failure: false
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      allow_failure: false
    - if: $CI_COMMIT_BRANCH == "master"
      allow_failure: false
    - when: always

test-nightly:
  stage: test
  script:
    - rustup override set nightly
    - cargo +nightly test --verbose
  allow_failure: true

test-stable:
  stage: test
  script:
    - cargo test --verbose

build-debug-nightly:
  stage: build-debug
  script:
    - rustup override set nightly
    - cargo +nightly build --verbose
  allow_failure: true

build-debug-stable:
  stage: build-debug
  script:
    - cargo build --verbose

build-release-nightly:
  stage: build-release
  script:
    - rustup override set nightly
    - cargo +nightly build --release --verbose
  allow_failure: true

build-release-stable:
  stage: build-release
  script:
    - cargo build --release --verbose
